MikeFunk\DoctrineExample\Entities\Bug:
  type: entity
  repositoryClass: MikeFunk\DoctrineExample\Repositories\BugRepository
  table: bugs
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created:
      type: datetime
    status:
      type: string
    description:
      type: string
  manyToOne:
    reporter:
      targetEntity: User
      inversedBy: reportedBugs
    engineer:
      targetEntity: User
      inversedBy: assignedBugs
  manyToMany:
    products:
      targetEntity: Product
